### ISSUE TITLE
Totally broken in Meteor 1.3

### ISSUE THREAD

**Issue by ffxsam** [dburles/meteor-eslint#8]
Upon just adding the package to my project:

```
   While linting files with dburles:eslint for the app (Server):
   /tools/isobuild/build-plugin.js:476:14: Object [object Object] has no method
   'getFileOptions'
   at [object Object].error (/tools/isobuild/build-plugin.js:476:14)
   at packages/eslint/plugin/eslint.js:126:1
   at Array.forEach (native)
   at reportErrors (packages/eslint/plugin/eslint.js:125:1)
   at packages/eslint/plugin/eslint.js:119:1
   at Array.forEach (native)
   at EsLintLinter.processFilesForPackage
   (packages/eslint/plugin/eslint.js:104:1)
```

**Comment by dburles** [comment]
Thanks, yeah I haven't yet tested it with 1.3

**Comment by klaseskilson** [comment]
It works fine for me using 1.3. @ffxsam, have you tested it since the non-beta version was released?

**Comment by ffxsam** [comment]
I tried again, and it's doing very odd things:

```
   While linting files with dburles:eslint for the app (Client):
   features/SomeFeature/lib/methods.js:1:2: Illegal import declaration
   lib/collections/some-collection.js:1:2: Illegal import declaration
```

It doesn't like totally basic ES6:

``` javascript
import { Mongo } from 'meteor/mongo';
import { Astro } from 'meteor/jagi:astronomy';
import { Validators } from 'meteor/jagi:astronomy-validators';
```

Yet running `eslint` manually yields no issues.

**Comment by dburles** [comment]
Hey @ffxsam update to 1.1.0, also take a look here: https://github.com/dburles/meteor-lint-config-example

If you haven't already done so, you should setup eslint locally [see here](http://guide.meteor.com/code-style.html#eslint).

Your local `.eslintrc` should look something like: 

``` json
{
  "extends": "airbnb",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module"
  }
}
```

If there's no `.eslintrc` found in your project, this package will use some similar defaults (minus airbnb).

**Comment by ffxsam** [comment]
I do have an `.eslintrc` but I don't think I have the eslint/meteor addons. I'll check that out and report back (I'm sure it'll work) :) Thanks!

**Comment by dburles** [comment]
Also to note, I've updated the package to use the latest version of eslint and the config changes slightly from prior to 2.0, so your config may require updating, here's the [migration guide](http://eslint.org/docs/user-guide/migrating-to-2.0.0#language-options)

**Comment by ffxsam** [comment]
Still no luck. I keep getting these errors in every file:

```
   client/layouts/MainLayout.js:1:1: Definition for rule
   'react/jsx-no-duplicate-props' was not found
   client/layouts/MainLayout.js:1:1: Definition for rule
   'react/no-direct-mutation-state' was not found
   client/layouts/MainLayout.js:1:1: Definition for rule 'react/no-is-mounted'
   was not found
```

**Comment by HenriBeck** [comment]
@ffxsam Meteor 1.3 fully supports npm now so you don't need the wrapper packages. If you dont already have a package.json do:
 `npm init`

Then run 
`npm i --save-dev eslint eslint-plugin-react eslint-plugin-meteor eslint-config-airbnb` 

This will install eslint, the eslint react plugin, the eslint meteor plugin and the airbnb config.
Then you can do:
`eslint .`

**Comment by dburles** [comment]
yeah i have been considering deprecating this package in favour of that

**Comment by ffxsam** [comment]
Yeah, but your package actually integrates into Meteor and dumps warnings/errors to the console and also prevents the app from running. Hmm.. maybe that's a little too forceful though. ;) I'm cool either way. Thanks for your contribution, David!

**Comment by abernix** [comment]
Found this because of meteor/meteor#6843 which looks like it might be causing problems for some people.

@ffxsam Meteor Guide already recommends installing eslint with eslintrc, airbnb style and includes setting up the editor for real-time linting.  At that point you're literally just double-linting on every change and doubling up on CPU cycles.  If you need to prevent commiting unlinted code, git hooks are probably the next best bet, followed by linting on CI servers.

I might agree with deprecation.  No offense of course, this looks like it served a good purpose for a minute.

**Comment by ffxsam** [comment]
@abernix At this point, I totally agree.
